env:
  global:
    - CC_TEST_REPORTER_ID=81e42661a39fae978969b4a10f6cc0a629f613a3d88faaf8fa36750a02f00fa0

language: node_js

node_js:
  - 4
  - 6
  - 8
  - 9

cache: yarn

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - yarn lint
  - yarn build

script:
  - yarn test:coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
